### ISSUE TITLE
How to pass page item as parameter in sql query

### ISSUE THREAD

**Issue by apexysatish** [aldocano29/AmandaDocxPrinter#10]
I have query and i want pass particular page item as a parameter how i achieve???

**Comment by aldocano29** [comment]
Have you tried the procedure explained in the readme? is it giving you any error? if so, could you upload a sample apex application and send me the credentials so I could give it a look?

**Comment by apexysatish** [comment]
sample apex application credentials 
Oracle Apex Online  credentials 
https://apex.oracle.com
Workspace:- hindu_bussiness
Username:- test
Password:- admin123
Application Number:-2947
Page Number:-1

Thanks For Reply

**Comment by aldocano29** [comment]
Done, you were not submitting the items, so the datasource could not access the value of the items you were trying to reference.
