### ISSUE TITLE
Can we store download file into table using this plugin

### ISSUE THREAD

**Issue by apexysatish** [aldocano29/AmandaDocxPrinter#11]
Hello Aldo Cano,
I have one question can we store downloaded file into database table.actually when we click on download button i want to store word file into my database table. can you please help me out or any suggestion how we can do it.

**Comment by aldocano29** [comment]
You'd have to modify the plugin's source code, because it was made to download the word file directly.

**Comment by sattuvirus** [comment]
where call insert process or statement execute into the plugin code ?
