### ISSUE TITLE
2 SQL files for packages not available on Git...

### ISSUE THREAD

**Issue by APEX-DevMan** [aldocano29/AmandaDocxPrinter#12]
After installing the application and viewing the source files, you mention in your README.md, "Run the **PK_AMANDASOFT_PLUGINS_SPEC.sql** and **PK_AMANDASOFT_PLUGINS_BODY.sql** files from the **plslq** directory to create the Package (inside the Application Schema) used by this plugin." yet those two files do not exist in the PLSQL folder or any other folder in the solution.

Please advise as the application's page 3 does not render due to missing packages. 👎 
![2019-12-18_7-49-03](https://user-images.githubusercontent.com/59018658/71087834-1e318300-216b-11ea-848b-e1f35bf5f5b8.png)

**Comment by aldocano29** [comment]
Which release are you looking at?

The latest one says (in the installation section):
"Import Plugin File dynamic_action_plugin_com_amandasoft_docxprinter.sql from the main directory into your Application."

**Comment by APEX-DevMan** [comment]
That is the first step and it worked fine. That does not change my questions where even in the latest version 1.6.1, the source PLSQL folder is missing the sql files to create the packages. That means page 3 in your demo application cannot render due to missing packages. That also mean I cannot use the DataSource Analyzer in your demo apps navigation (takes u to page 3). 
Next, I am using APEX 5.1.1. I have the plugin installed and available, I have my hidden page items for datasources, I have my template setup and uploaded to the static files, when I click my print button and DA fires, it produces an error but the error is not visible on the page, I had to use the inspector and find in your JS how it was trying to produce a page level error and then read the error info. The issue appears to be that the opacity on ".t-Alert--page.t-Alert--success" classes is set to 0. Once i unchecked the opacity the error was visible. My error states I am missing a right parenthesis but both my data sources have all required open and close parens so the error is not telling me where (what line) the error is occurring on to troubleshoot it. 
Any assistance would be great. I really want to get this working as it appears to be a great way to have a header and footer on each page when printing an interactive report!

**Comment by aldocano29** [comment]
updated the demo application and installation description in readme.

The Plugin works, but the demo application inside this repository was never updated, I only updated the one in the Oracle APEX Workspace.

**Comment by APEX-DevMan** [comment]
Now the 1.6.2 is not compatible any longer with my APEX v5.1.1.
![version-error](https://user-images.githubusercontent.com/59018658/71100041-4f697d80-2182-11ea-9634-f319ed271ab4.png)

**Comment by aldocano29** [comment]
The application was exported from apex 19.2 (the only one I had available at the time being).  As I said before, the plugin does work, you can still use the demo application referenced in the readme.

**Comment by APEX-DevMan** [comment]
It's impossible to use your demo applications validator on select statements from my application, That's the only thing the demo application is remotely useful for. The images in the source are the only other things u have in the in demo app and they are available when u download the zip. And i've been developing APEX applications for 5+ years so far and the plugin definitely does not work for me in 5.1.1 and does not provide enough setup/configuration/help to troubleshoot any issues. I have wasted over 8 hours on this plugin so far and still have no clue if it will even do what im looking for until I can see successful output. 👎

**Comment by aldocano29** [comment]
The plugin does work. Set a workspace on apex.oracle.com with the last version of the plugin installed, and an application with a sample of what you're trying to accomplish (Including templates and datasources).  Provide me the credentials to access that workspace, in that way I can help you out and tell you what's wrong.

So far you have not provided me any information about what the problem is with your application at the moment of using the pluging itself.

**Comment by APEX-DevMan** [comment]
Sorry Aldo, I am just getting really frustrated with it. I am setting up the application on apex.oracle.com now so I can attempt to use the plugin in the demo app before i add the complexity of my select statements. Stay tuned for an update and I'll grant you access once i get it setup...  Thanks for all the quick replies so far.

**Comment by APEX-DevMan** [comment]
OK it's setup and still not working. You login credentials are:
Workspace:  ANG-E3
UserName:  Aldo
Password:   Apex1234

My test is on Page 9 when i have a single button and some verbiage along with a screen shot from your demo.

**Comment by aldocano29** [comment]
I can't access at the moment. I'm getting an error from the apex workspace , it seems to be down or something. I will try again later

**Comment by aldocano29** [comment]
Invalid credentials

**Comment by APEX-DevMan** [comment]
Then you are typing something wrong. I just tried them again and they worked fine for me. Capital A in Apex1234 for the password.

**Comment by aldocano29** [comment]
The tables demo_customer, demo_orders, etc do not exist anymore. For that reason, none of the datasources work. They are all consulting those tables.

**Comment by aldocano29** [comment]
I created them for you, now it's working
