### ISSUE TITLE
html docx problem

### ISSUE THREAD

**Issue by jasonyisong** [aldocano29/AmandaDocxPrinter#2]
we have html like this：
`<p>your plugin <u>is<span style="color:#ff0000"> so</span></u>&nbsp;good</p >`

and use plugin download  , find HtmlContent docx file html "is so"format not right,  and check code is ：
`<w:p><w:r><w:t xml:space="preserve">your plugin </w:t></w:r><w:r><w:rPr><w:u w:val="single"/><w:color w:val="ff0000"/></w:rPr><w:t xml:space="preserve">is so</w:t></w:r><w:r><w:t xml:space="preserve"> good</w:t></w:r></w:p>`

Pls help !
thanks.

**Comment by aldocano29** [comment]
I just tried it on the demo app and it worked flawlesly. May I ask what version of Word are you using, or maybe give me some more enviroment information.


![screenshot](https://user-images.githubusercontent.com/20285968/35870963-043af122-0b31-11e8-91d9-1370f984e04e.png)

**Comment by jasonyisong** [comment]
thanks for your help.
we face problem is html font color “is” is not red, and htmlcontent docx show “is” is red. that' right？ And we use Word 2016, oracle 11.2.0.4 , apex 5.1.3 .

**Comment by aldocano29** [comment]
Oh now I understand what you mean, I will take a look at it.

**Comment by aldocano29** [comment]
Ok, Considering:  

<p>your plugin <u>is<span style="color:#ff0000"> so</span></u>&nbsp;good</p >

 "is" and "so" are both part of the same **\<u\>**

 element... So when the code translates this to word XML, it gives the attribute "color" inside the **\<span\>** to the whole **\<u\>** element....

Maybe you could try the following, which actually worked for me:

**\<p\>your plugin \<u\>is\</u\>\<u\>\<span style="color:#ff0000"\> so\</span\>\</u\>\&nbsp;good\</p \>**

**Comment by jasonyisong** [comment]
yes，I chang html code and test is ok，but apex rich text can’t control input content like that，so i want to know have any way to auto translates “<u>is</u><u><span style="color:#ff0000"> so</span></u>”.
anyway，thanks a lot！
