### ISSUE TITLE
Datasource item

### ISSUE THREAD

**Issue by Damavikoff** [aldocano29/AmandaDocxPrinter#3]
Hi.

I have a question regarding datasource item usage. The problem is that it's looks like the plugin takes item's value on page load and does not react on changes for this item. I mean, for example, if i change the item's value via 'Set Value' event, the plugin ignores changed value and tries to use value which was taken when page was loaded. Is there any way to avoid this and make it work dynamically?

Thank you in advance.

**Comment by aldocano29** [comment]
Could you set up an environment on apex.oracle.com and send me the credentials so I can give it a look?

**Comment by Damavikoff** [comment]
Please, take a look
https://apex.oracle.com/pls/apex/
workspace: **TESTUS**
username: **DEMO**
passwords: **demo**
application: **TST_APP**

**Comment by aldocano29** [comment]
Ok, now I understand what you meant.  Yes, I can change it and make it dynamic, but I have to sit down  to change the code for the plugin and run some tests so I can then release it.

I might have it by the end of the week (depending on my workload).

I will let you know.

Have a great one!

**Comment by Damavikoff** [comment]
Thank you.

**Comment by aldocano29** [comment]
Hi, sorry for the late answer.


I uploaded an update for the plugin (I think I uploaded it right this time...) could you give it a try and let me know if it works for you?

**Comment by Damavikoff** [comment]
hi. yes, it works good. thank you for your great work.
the only thing is that it seems you forgot to put package spec and body inside the archive. (if they are still required)
Once again, thanks a lot.

**Comment by aldocano29** [comment]
Not required anymore thanks to you :)
