### ISSUE TITLE
Error: Identifier 'PK_AMANDASOFT_PLUGINS.FC_RENDER_DOCXPRINTER' must be declared

### ISSUE THREAD

**Issue by Vincent-Cheng** [aldocano29/AmandaDocxPrinter#6]
Hi, when installing the f100.sql and runs it, when clicking "Template Checkup", the following error raised:

https://www.evernote.com/l/AFDGcObWNwtLcZDmGCXGkP6L2VbGfRXUt6Y

APEX version: 18.2.0.00.12

What did we miss? thanks.

**Comment by aldocano29** [comment]
Template checkup is not usable ATM, and probable wont be. The plugin works, the demo application was never updated to stop showing the Template checkup functionality.
