### ISSUE TITLE
Sorry In plsql can't find PK_AMANDASOFT_PLUGINS

### ISSUE THREAD

**Issue by loho1968** [aldocano29/AmandaDocxPrinter#7]
Error: Identifier 'PK_AMANDASOFT_PLUGINS.FC_RENDER_DOCXPRINTER' must be declared

**Comment by aldocano29** [comment]
The plugin works, the demo application was never updated to stop showing the Template checkup functionality, which is probably the culprit for that message... If it is not, let me know
