### ISSUE TITLE
How to Show Image with query using this Plugin 

### ISSUE THREAD

**Issue by apexysatish** [aldocano29/AmandaDocxPrinter#9]
Hello Aldo Cano,
This plugin is good but now i want to show image in doc file please could you help me out.it's urgent i am using image tag into doc template file {%image} and image URL store into one item  and that item pass into dynamic action data source but image not show.

**Comment by aldocano29** [comment]
This plugin still doesn't support image uploading. Maybe in a future release, but not at the moment.
